# Generated by Django 6.0.5 on 2026-05-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mass_type',
            field=models.CharField(choices=[('kg', 'kg'), ('gr', 'gr'), ('l', 'l')], null=True),
        ),
    ]
