# Generated by Django 6.0.5 on 2026-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_mass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mass',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mass_type',
            field=models.CharField(choices=[('kg', 'kg'), ('gr', 'gr'), ('litr', 'litr')], null=True),
        ),
    ]
