# Generated by Django 6.0.5 on 2026-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready for pickup/delivery'), ('delivering', 'Delivering'), ('done', 'Done'), ('canceled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
