# Generated by Django 6.0.5 on 2026-05-12 16:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userlocation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
